[database]
image = "postgres:12"

[database.ports]
"5432/tcp" = ""

[database.environment]
POSTGRES_USER = "bebop"
POSTGRES_PASSWORD = "secret"
POSTGRES_DB = "bebop"

[database.export]
SQLALCHEMY_DATABASE_URI = "postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{HOST}:{PORT;5432/tcp}/{POSTGRES_DB}"
POSTGRES_MAIN_USER = "{POSTGRES_USER}"
POSTGRES_MAIN_PASSWORD = "{POSTGRES_USER}"
POSTGRES_MAIN_HOST = "{POSTGRES_USER}"
POSTGRES_MAIN_RDS_HOST = "{POSTGRES_USER}"
POSTGRES_MAIN_PORT = "{PORT;5432/tcp}"
POSTGRES_MAIN_DBNAME = "{POSTGRES_DB}"
